/**
 * @fileoverview gRPC-Web generated client stub for journal.admin
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: admin.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as admin_pb from './admin_pb'; // proto import: "admin.proto"


export class JournalServerAdminServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListShard = new grpcWeb.MethodDescriptor(
    '/journal.admin.JournalServerAdminService/ListShard',
    grpcWeb.MethodType.UNARY,
    admin_pb.ListShardRequest,
    admin_pb.ListShardReply,
    (request: admin_pb.ListShardRequest) => {
      return request.serializeBinary();
    },
    admin_pb.ListShardReply.deserializeBinary
  );

  listShard(
    request: admin_pb.ListShardRequest,
    metadata?: grpcWeb.Metadata | null): Promise<admin_pb.ListShardReply>;

  listShard(
    request: admin_pb.ListShardRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: admin_pb.ListShardReply) => void): grpcWeb.ClientReadableStream<admin_pb.ListShardReply>;

  listShard(
    request: admin_pb.ListShardRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: admin_pb.ListShardReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/journal.admin.JournalServerAdminService/ListShard',
        request,
        metadata || {},
        this.methodDescriptorListShard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/journal.admin.JournalServerAdminService/ListShard',
    request,
    metadata || {},
    this.methodDescriptorListShard);
  }

  methodDescriptorListSegment = new grpcWeb.MethodDescriptor(
    '/journal.admin.JournalServerAdminService/ListSegment',
    grpcWeb.MethodType.UNARY,
    admin_pb.ListSegmentRequest,
    admin_pb.ListSegmentReply,
    (request: admin_pb.ListSegmentRequest) => {
      return request.serializeBinary();
    },
    admin_pb.ListSegmentReply.deserializeBinary
  );

  listSegment(
    request: admin_pb.ListSegmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<admin_pb.ListSegmentReply>;

  listSegment(
    request: admin_pb.ListSegmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: admin_pb.ListSegmentReply) => void): grpcWeb.ClientReadableStream<admin_pb.ListSegmentReply>;

  listSegment(
    request: admin_pb.ListSegmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: admin_pb.ListSegmentReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/journal.admin.JournalServerAdminService/ListSegment',
        request,
        metadata || {},
        this.methodDescriptorListSegment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/journal.admin.JournalServerAdminService/ListSegment',
    request,
    metadata || {},
    this.methodDescriptorListSegment);
  }

}

