# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

settings:
  skipIfBot: false
  removeUnmatchedLabels: false

rules:
  pr:
    - label: kind:feat
      matches:
        - operator: any
          conditions:
            - title: /^feat(\(.*\))?:/i

    - label: kind:bug
      matches:
        - operator: any
          conditions:
            - title: /^fix(\(.*\))?:/i

    - label: kind:test
      matches:
        - operator: any
          conditions:
            - title: /^test(\(.*\))?:/i

    - label: kind:refactor
      matches:
        - operator: any
          conditions:
            - title: /^refactor(\(.*\))?:/i

    - label: kind:chore
      matches:
        - operator: any
          conditions:
            - title: /^chore(\(.*\))?:/i

    - label: kind:style
      matches:
        - operator: any
          conditions:
            - title: /^style(\(.*\))?:/i

    - label: kind:docs
      matches:
        - operator: any
          conditions:
            - title: /^docs(\(.*\))?:/i

    - label: kind:perf
      matches:
        - operator: any
          conditions:
            - title: /^perf(\(.*\))?:/i

    - label: kind:build
      matches:
        - operator: any
          conditions:
            - title: /^build(\(.*\))?:/i

    - label: kind:ci
      matches:
        - operator: any
          conditions:
            - title: /^ci(\(.*\))?:/i

    - label: kind:revert
      matches:
        - operator: any
          conditions:
            - title: /^revert(\(.*\))?:/i

  issue:
    # subtask issues: [RBIP-*/MINOR][Style/Refactor/Performance/Docs/Test/Build/CI/Chore][Subtask]
    - label: kind:style
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Style\]\[Subtask\]/
            - title: /^\[Style\]/

    - label: kind:refactor
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Refactor\]\[Subtask\]/
            - title: /^\[Refactor\]/

    - label: kind:perf
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Performance\]\[Subtask\]/
            - title: /^\[Performance\]/

    - label: kind:docs
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Docs\]\[Subtask\]/
            - title: /^\[Docs\]/

    - label: kind:test
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Test\]\[Subtask\]/
            - title: /^\[Test\]/

    - label: kind:build
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Build\]\[Subtask\]/
            - title: /^\[Build\]/

    - label: kind:ci
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[CI\]\[Subtask\]/
            - title: /^\[CI\]/

    - label: kind:chore
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\]\[Chore\]\[Subtask\]/
            - title: /^\[Chore\]/

    - label: kind:subtask
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\].*\[Subtask\]/

    - label: enhancement
      matches:
        - operator: any
          conditions:
            - title: /^\[(Style|Refactor|Performance|Docs|Test|Build|CI|Chore)\]/

    - label: kind:bug
      matches:
        - operator: any
          conditions:
            - title: /^\[BUG\]/

    - label: kind:feat
      matches:
        - operator: any
          conditions:
            - title: /^\[Feat\]/

    - label: kind:umbrella
      matches:
        - operator: any
          conditions:
            - title: /^\[(RBIP-\d+|MINOR)\](?!.*\[Subtask\])/
