# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cluster_name = "mqtt-broker"
broker_id = 1
grpc_port = 9981
placement_center = ["127.0.0.1:1228"]

[network_port]
local_ip = "127.0.0.1"
tcp_port = 1883
tcps_port = 8883
websocket_port = 8093
websockets_port = 8094
quic_port = 9083
tls_cert = "./certs/cert.pem"
tls_key = "./certs/key.pem"

[network_thread]
accept_thread_num = 10
handler_thread_num = 10
response_thread_num = 10
max_connection_num = 5000000
request_queue_size = 2000
response_queue_size = 2000
lock_max_try_mut_times = 30
lock_try_mut_sleep_time_ms = 50

[auth_storage]
storage_type = "placement"

[prometheus]
enable = true
model = "pull"
port = 9091
push_gateway_server = "127.0.0.1:8081"
interval = 10
header = ""

[system]
heartbeat_timeout = "10s"
runtime_worker_threads = 4
default_user = "admin"
default_password = "pwd123"

[system_monitor]
enable = true
os_cpu_check_interval_ms = 60000
os_cpu_high_watermark = 70.0
os_cpu_low_watermark = 50.0
os_memory_check_interval_ms = 60
os_memory_high_watermark = 80.0

[offline_messages]
enable = true
expire_ms = 3600
max_messages_num = 1000

[storage]
storage_type = "memory"

[log]
log_config = "./mqtt-server/mqtt-tracing.toml"
log_path = "./robust-data-test/mqtt-broker/logs"

[pprof]
enable = false
port = 6060
frequency = 100
