// Copyright 2023 RobustMQ Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use kafka_protocol::messages::{
    AddOffsetsToTxnRequest,
    AddOffsetsToTxnResponse,
    AddPartitionsToTxnRequest,
    AddPartitionsToTxnResponse,
    AlterClientQuotasRequest,
    AlterClientQuotasResponse,
    AlterConfigsRequest,
    AlterConfigsResponse,
    AlterPartitionReassignmentsRequest,
    AlterPartitionReassignmentsResponse,
    AlterReplicaLogDirsRequest,
    AlterReplicaLogDirsResponse,
    AlterShareGroupOffsetsRequest,
    AlterShareGroupOffsetsResponse,
    AlterUserScramCredentialsRequest,
    AlterUserScramCredentialsResponse,
    ApiVersionsRequest,
    ApiVersionsResponse,
    ConsumerGroupDescribeRequest,
    ConsumerGroupDescribeResponse,
    // Next-Generation Consumer Group Protocol (KIP-848)
    ConsumerGroupHeartbeatRequest,
    ConsumerGroupHeartbeatResponse,
    CreateAclsRequest,
    CreateAclsResponse,
    // Delegation Token Authentication
    CreateDelegationTokenRequest,
    CreateDelegationTokenResponse,
    CreatePartitionsRequest,
    CreatePartitionsResponse,
    // Topic / Partition Management
    CreateTopicsRequest,
    CreateTopicsResponse,
    DeleteAclsRequest,
    DeleteAclsResponse,
    DeleteGroupsRequest,
    DeleteGroupsResponse,
    DeleteRecordsRequest,
    DeleteRecordsResponse,
    DeleteShareGroupOffsetsRequest,
    DeleteShareGroupOffsetsResponse,
    DeleteTopicsRequest,
    DeleteTopicsResponse,
    // ACL Access Control
    DescribeAclsRequest,
    DescribeAclsResponse,
    // Quota Management
    DescribeClientQuotasRequest,
    DescribeClientQuotasResponse,
    DescribeClusterRequest,
    DescribeClusterResponse,
    // Configuration Management
    DescribeConfigsRequest,
    DescribeConfigsResponse,
    DescribeDelegationTokenRequest,
    DescribeDelegationTokenResponse,
    DescribeGroupsRequest,
    DescribeGroupsResponse,
    DescribeLogDirsRequest,
    DescribeLogDirsResponse,
    DescribeProducersRequest,
    DescribeProducersResponse,
    DescribeShareGroupOffsetsRequest,
    DescribeShareGroupOffsetsResponse,
    DescribeTopicPartitionsRequest,
    DescribeTopicPartitionsResponse,
    DescribeTransactionsRequest,
    DescribeTransactionsResponse,
    DescribeUserScramCredentialsRequest,
    DescribeUserScramCredentialsResponse,
    ElectLeadersRequest,
    ElectLeadersResponse,
    EndTxnRequest,
    EndTxnResponse,
    ExpireDelegationTokenRequest,
    ExpireDelegationTokenResponse,
    FetchRequest,
    FetchResponse,
    FindCoordinatorRequest,
    FindCoordinatorResponse,
    // Client Telemetry
    GetTelemetrySubscriptionsRequest,
    GetTelemetrySubscriptionsResponse,
    HeartbeatRequest,
    HeartbeatResponse,
    IncrementalAlterConfigsRequest,
    IncrementalAlterConfigsResponse,
    // Transaction Support
    InitProducerIdRequest,
    InitProducerIdResponse,
    JoinGroupRequest,
    JoinGroupResponse,
    LeaveGroupRequest,
    LeaveGroupResponse,
    ListConfigResourcesRequest,
    ListConfigResourcesResponse,
    ListGroupsRequest,
    ListGroupsResponse,
    ListOffsetsRequest,
    ListOffsetsResponse,
    ListPartitionReassignmentsRequest,
    ListPartitionReassignmentsResponse,
    ListTransactionsRequest,
    ListTransactionsResponse,
    MetadataRequest,
    MetadataResponse,
    // Consumer Group Management
    OffsetCommitRequest,
    OffsetCommitResponse,
    OffsetDeleteRequest,
    OffsetDeleteResponse,
    OffsetFetchRequest,
    OffsetFetchResponse,
    // Operations & Administration
    OffsetForLeaderEpochRequest,
    OffsetForLeaderEpochResponse,
    // Core Data Plane
    ProduceRequest,
    ProduceResponse,
    PushTelemetryRequest,
    PushTelemetryResponse,
    RenewDelegationTokenRequest,
    RenewDelegationTokenResponse,
    // Headers
    RequestHeader,
    ResponseHeader,
    SaslAuthenticateRequest,
    SaslAuthenticateResponse,
    // Connection & Authentication
    SaslHandshakeRequest,
    SaslHandshakeResponse,
    ShareAcknowledgeRequest,
    ShareAcknowledgeResponse,
    ShareFetchRequest,
    ShareFetchResponse,
    ShareGroupDescribeRequest,
    ShareGroupDescribeResponse,
    // Share Group (KIP-932)
    ShareGroupHeartbeatRequest,
    ShareGroupHeartbeatResponse,
    SyncGroupRequest,
    SyncGroupResponse,
    TxnOffsetCommitRequest,
    TxnOffsetCommitResponse,
    UpdateFeaturesRequest,
    UpdateFeaturesResponse,
};

#[derive(Debug, Clone, PartialEq)]
pub struct KafkaPacketWrapper {
    pub api_version: i16,
    pub header: KafkaHeader,
    pub packet: KafkaPacket,
}

#[derive(Debug, Clone, PartialEq)]
pub enum KafkaHeader {
    Request(RequestHeader),
    Response(ResponseHeader),
}

#[derive(Debug, Clone, PartialEq)]
pub enum KafkaPacket {
    // Core Data Plane
    ProduceReq(ProduceRequest),
    ProduceResponse(ProduceResponse),
    FetchReq(FetchRequest),
    FetchResponse(FetchResponse),
    ListOffsetsReq(ListOffsetsRequest),
    ListOffsetsResponse(ListOffsetsResponse),
    MetadataReq(MetadataRequest),
    MetadataResponse(MetadataResponse),
    // Consumer Group Management
    OffsetCommitReq(OffsetCommitRequest),
    OffsetCommitResponse(OffsetCommitResponse),
    OffsetFetchReq(OffsetFetchRequest),
    OffsetFetchResponse(OffsetFetchResponse),
    FindCoordinatorReq(FindCoordinatorRequest),
    FindCoordinatorResponse(FindCoordinatorResponse),
    JoinGroupReq(JoinGroupRequest),
    JoinGroupResponse(JoinGroupResponse),
    HeartbeatReq(HeartbeatRequest),
    HeartbeatResponse(HeartbeatResponse),
    LeaveGroupReq(LeaveGroupRequest),
    LeaveGroupResponse(LeaveGroupResponse),
    SyncGroupReq(SyncGroupRequest),
    SyncGroupResponse(SyncGroupResponse),
    DescribeGroupsReq(DescribeGroupsRequest),
    DescribeGroupsResponse(DescribeGroupsResponse),
    ListGroupsReq(ListGroupsRequest),
    ListGroupsResponse(ListGroupsResponse),
    DeleteGroupsReq(DeleteGroupsRequest),
    DeleteGroupsResponse(DeleteGroupsResponse),
    OffsetDeleteReq(OffsetDeleteRequest),
    OffsetDeleteResponse(OffsetDeleteResponse),
    // Connection & Authentication
    SaslHandshakeReq(SaslHandshakeRequest),
    SaslHandshakeResponse(SaslHandshakeResponse),
    ApiVersionReq(ApiVersionsRequest),
    ApiVersionResponse(ApiVersionsResponse),
    SaslAuthenticateReq(SaslAuthenticateRequest),
    SaslAuthenticateResponse(SaslAuthenticateResponse),
    // Topic / Partition Management
    CreateTopicsReq(CreateTopicsRequest),
    CreateTopicsResponse(CreateTopicsResponse),
    DeleteTopicsReq(DeleteTopicsRequest),
    DeleteTopicsResponse(DeleteTopicsResponse),
    DeleteRecordsReq(DeleteRecordsRequest),
    DeleteRecordsResponse(DeleteRecordsResponse),
    CreatePartitionsReq(CreatePartitionsRequest),
    CreatePartitionsResponse(CreatePartitionsResponse),
    // Configuration Management
    DescribeConfigsReq(DescribeConfigsRequest),
    DescribeConfigsResponse(DescribeConfigsResponse),
    AlterConfigsReq(AlterConfigsRequest),
    AlterConfigsResponse(AlterConfigsResponse),
    IncrementalAlterConfigsReq(IncrementalAlterConfigsRequest),
    IncrementalAlterConfigsResponse(IncrementalAlterConfigsResponse),
    // Transaction Support
    InitProducerIdReq(InitProducerIdRequest),
    InitProducerIdResponse(InitProducerIdResponse),
    AddPartitionsToTxnReq(AddPartitionsToTxnRequest),
    AddPartitionsToTxnResponse(AddPartitionsToTxnResponse),
    AddOffsetsToTxnReq(AddOffsetsToTxnRequest),
    AddOffsetsToTxnResponse(AddOffsetsToTxnResponse),
    EndTxnReq(EndTxnRequest),
    EndTxnResponse(EndTxnResponse),
    TxnOffsetCommitReq(TxnOffsetCommitRequest),
    TxnOffsetCommitResponse(TxnOffsetCommitResponse),
    DescribeTransactionsReq(DescribeTransactionsRequest),
    DescribeTransactionsResponse(DescribeTransactionsResponse),
    ListTransactionsReq(ListTransactionsRequest),
    ListTransactionsResponse(ListTransactionsResponse),
    // ACL Access Control
    DescribeAclsReq(DescribeAclsRequest),
    DescribeAclsResponse(DescribeAclsResponse),
    CreateAclsReq(CreateAclsRequest),
    CreateAclsResponse(CreateAclsResponse),
    DeleteAclsReq(DeleteAclsRequest),
    DeleteAclsResponse(DeleteAclsResponse),
    // Quota Management
    DescribeClientQuotasReq(DescribeClientQuotasRequest),
    DescribeClientQuotasResponse(DescribeClientQuotasResponse),
    AlterClientQuotasReq(AlterClientQuotasRequest),
    AlterClientQuotasResponse(AlterClientQuotasResponse),
    DescribeUserScramCredentialsReq(DescribeUserScramCredentialsRequest),
    DescribeUserScramCredentialsResponse(DescribeUserScramCredentialsResponse),
    AlterUserScramCredentialsReq(AlterUserScramCredentialsRequest),
    AlterUserScramCredentialsResponse(AlterUserScramCredentialsResponse),
    // Delegation Token Authentication
    CreateDelegationTokenReq(CreateDelegationTokenRequest),
    CreateDelegationTokenResponse(CreateDelegationTokenResponse),
    RenewDelegationTokenReq(RenewDelegationTokenRequest),
    RenewDelegationTokenResponse(RenewDelegationTokenResponse),
    ExpireDelegationTokenReq(ExpireDelegationTokenRequest),
    ExpireDelegationTokenResponse(ExpireDelegationTokenResponse),
    DescribeDelegationTokenReq(DescribeDelegationTokenRequest),
    DescribeDelegationTokenResponse(DescribeDelegationTokenResponse),
    // Client Telemetry
    GetTelemetrySubscriptionsReq(GetTelemetrySubscriptionsRequest),
    GetTelemetrySubscriptionsResponse(GetTelemetrySubscriptionsResponse),
    PushTelemetryReq(PushTelemetryRequest),
    PushTelemetryResponse(PushTelemetryResponse),
    ListConfigResourcesReq(ListConfigResourcesRequest),
    ListConfigResourcesResponse(ListConfigResourcesResponse),
    // Operations & Administration
    OffsetForLeaderEpochReq(OffsetForLeaderEpochRequest),
    OffsetForLeaderEpochResponse(OffsetForLeaderEpochResponse),
    AlterReplicaLogDirsReq(AlterReplicaLogDirsRequest),
    AlterReplicaLogDirsResponse(AlterReplicaLogDirsResponse),
    DescribeLogDirsReq(DescribeLogDirsRequest),
    DescribeLogDirsResponse(DescribeLogDirsResponse),
    ElectLeadersReq(ElectLeadersRequest),
    ElectLeadersResponse(ElectLeadersResponse),
    AlterPartitionReassignmentsReq(AlterPartitionReassignmentsRequest),
    AlterPartitionReassignmentsResponse(AlterPartitionReassignmentsResponse),
    ListPartitionReassignmentsReq(ListPartitionReassignmentsRequest),
    ListPartitionReassignmentsResponse(ListPartitionReassignmentsResponse),
    UpdateFeaturesReq(UpdateFeaturesRequest),
    UpdateFeaturesResponse(UpdateFeaturesResponse),
    DescribeClusterReq(DescribeClusterRequest),
    DescribeClusterResponse(DescribeClusterResponse),
    DescribeProducersReq(DescribeProducersRequest),
    DescribeProducersResponse(DescribeProducersResponse),
    DescribeTopicPartitionsReq(DescribeTopicPartitionsRequest),
    DescribeTopicPartitionsResponse(DescribeTopicPartitionsResponse),
    // Next-Generation Consumer Group Protocol (KIP-848)
    ConsumerGroupHeartbeatReq(ConsumerGroupHeartbeatRequest),
    ConsumerGroupHeartbeatResponse(ConsumerGroupHeartbeatResponse),
    ConsumerGroupDescribeReq(ConsumerGroupDescribeRequest),
    ConsumerGroupDescribeResponse(ConsumerGroupDescribeResponse),
    // Share Group (KIP-932)
    ShareGroupHeartbeatReq(ShareGroupHeartbeatRequest),
    ShareGroupHeartbeatResponse(ShareGroupHeartbeatResponse),
    ShareGroupDescribeReq(ShareGroupDescribeRequest),
    ShareGroupDescribeResponse(ShareGroupDescribeResponse),
    ShareFetchReq(ShareFetchRequest),
    ShareFetchResponse(ShareFetchResponse),
    ShareAcknowledgeReq(ShareAcknowledgeRequest),
    ShareAcknowledgeResponse(ShareAcknowledgeResponse),
    DescribeShareGroupOffsetsReq(DescribeShareGroupOffsetsRequest),
    DescribeShareGroupOffsetsResponse(DescribeShareGroupOffsetsResponse),
    AlterShareGroupOffsetsReq(AlterShareGroupOffsetsRequest),
    AlterShareGroupOffsetsResponse(AlterShareGroupOffsetsResponse),
    DeleteShareGroupOffsetsReq(DeleteShareGroupOffsetsRequest),
    DeleteShareGroupOffsetsResponse(DeleteShareGroupOffsetsResponse),
}
