# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cluster_name = "robustmq-3env"
broker_id = 2
broker_ip = "127.0.0.1"
roles = ["meta", "broker", "engine"]
grpc_port = 2228
http_port = 58082
meta_addrs = { 1 = "127.0.0.1:1228", 2 = "127.0.0.1:2228", 3 = "127.0.0.1:3228" }
data_path = "./data/broker-2/data"

[log]
log_config = "./config/logger.toml"
log_path = "./data/broker-2/logs"

[network]
accept_thread_num = 1
handler_thread_num = 64
queue_size = 5000
keep_alive_enable = false

[meta_runtime]
heartbeat_timeout_ms = 30000
heartbeat_check_time_ms = 1000
raft_write_timeout_sec = 30
offset_raft_group_num = 1
data_raft_group_num = 1

[mqtt_keep_alive]
enable = true
default_time = 180
max_time = 3600
default_timeout = 2

[message_storage]
storage_type = "EngineRocksDB"

[mqtt_system_topic]
interval_ms = 60000

[mqtt_offline_message]
enable = true
expire_ms = 3600000
max_messages_num = 100000

[storage_offset]
enable_cache = true

[storage_runtime]
tcp_port = 2779
max_segment_size = 1073741824
data_path = ["./data/broker-2/engine"]
io_thread_num = 4

[runtime]
tls_cert = "./config/certs/cert.pem"
tls_key = "./config/certs/key.pem"
server_worker_threads = 16
meta_worker_threads = 16
broker_worker_threads = 16

[mqtt_runtime]
default_user = "admin"
default_password = "robustmq"
durable_sessions_enable = false
secret_free_login = false
is_self_protection_status = false

[grpc_client]
channels_per_address = 4

[mqtt_server]
tcp_port = 2883
tls_port = 2885
websocket_port = 8283
websockets_port = 8285
quic_port = 9283

[nats_runtime]
tcp_port = 5222
tls_port = 5223
ws_port  = 5080
wss_port = 5443

[kafka_runtime]
tcp_port = 9192

[amqp_runtime]
tcp_port = 5772

[admin]
username = "admin"
password = "admin"
jwt_secret = "robustmq-change-me-in-production"
token_ttl_hours = 8
