[appenders.stdout]
kind = "Console"
level = "Info"

# [appenders.server]
# kind = "RollingFile"
# level = "Info"
# rotation = "Minutely"
# directory = "./logs/tests"
# prefix = "mqtt-server-"
# suffix = "log"
# max_log_files = 10

[appenders.slow_sub]
kind = "RollingFile"
level = "Info"
rotation = "Minutely"
directory = "./logs/tests"
prefix = "mqtt-slow_sub-"
suffix = "log"
max_log_files = 10
