# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Code Style

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"

# Cancel previous runs if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Grant necessary permissions for package access
permissions:
  contents: read
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  # Fast checks that don't need compilation cache
  rustfmt:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v5
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: cargo rust-fmt
        run: cargo fmt --all -- --check

  deny:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v5
      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.16.2
      - name: cargo deny check
        run: cargo-deny check licenses

  typos:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v5
      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli@1.27.3
      - name: typos check
        run: typos

  # Compilation checks with shared cache
  # Run cargo check and clippy together to share compilation cache
  compile-and-lint:
    runs-on: ubuntu-latest
    container:
      # 🚀 Use manually-maintained pre-built image with all dependencies!
      # Built from: docker/Dockerfile.deps
      # See docker/README.md for maintenance guide
      image: ghcr.io/robustmq/robustmq/rust-deps:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    env:
      CARGO_BUILD_JOBS: 10
      CARGO_INCREMENTAL: 1
      CARGO_TARGET_DIR: /build/target
      RUST_BACKTRACE: 1
      PROTOC: /usr/bin/protoc
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Install clippy
        run: rustup component add clippy
      
      - name: Cargo clippy
        # Clippy includes cargo check, so we skip separate check step
        # Dependencies already compiled in image, only check project code
        run: cargo clippy --workspace --all-targets --tests -- -D warnings
