# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Code Style

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check crate compiles
  linux-build-lib:
    name: cargo check
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-cache-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}  # Run tests

  rustfmt:
    runs-on: ubuntu-latest
    needs: [ linux-build-lib ]
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: install rustfmt
        run:  rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        name: rust-fmt
        with:
          command: fmt
          args: --all -- --check

  deny:
    needs: [ linux-build-lib ]
    container:
      image: amd64/rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: Install cargo-deny
        run: cargo install cargo-deny@0.16.2
      - name: cargo deny check
        run: cargo-deny check licenses

  typos:
    needs: [ linux-build-lib ]
    container:
      image: amd64/rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: Install typos
        run: cargo install typos-cli@1.27.3
      - name: typos check
        run: typos

  # this is compiling check
  cargo-compile-check:
    needs: [ linux-build-lib ]
    container:
      image: amd64/rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

  clippy:
    needs: [ linux-build-lib ]
    container:
      image: amd64/rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: Install clippy
        run:  rustup component add clippy
      - uses: actions-rs/cargo@v1
        name: rust-clippy
        with:
          command: clippy
          args: --all-targets --all-features --tests --benches -- -D warnings
