# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Journal Server Base Ig Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-tests:
    name: cargo test
    runs-on: ubuntu-latest
    timeout-minutes: 300
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up build configure
        uses: ./.github/actions/setup-builder
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          args: --locked
      - uses: actions/checkout@v3
      - name: Run tests
        run: sh ./scripts/journal-ig-test.sh dev
        # we need change shell scripts to product only one junit.xml
#      - name: Upload JUnit report
#        # Run this step even if the test step fails. Upload it right now because
#        # we're most interested in the JUnit report generated by the local
#        # version of nextest, not the latest release.
#        if: "!cancelled()"
#        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
#        with:
#          name: junit-unbutu.xml
#          path: |
#            target/nextest/ci/junit.xml
#          if-no-files-found: error
