# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Close Stale Issues and PRs

on:
  schedule:
    # Run daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          # Issue settings
          days-before-issue-stale: 720
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity for 720 days. It will be closed in 14 days if no further activity occurs.
            If you believe this issue is still relevant, please comment to keep it open.
          close-issue-message: >
            This issue has been automatically closed due to inactivity.
            If you believe this issue is still relevant, please reopen it or create a new issue.
          
          # PR settings
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: 'stale'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 7 days if no further activity occurs.
            Please rebase and resolve any conflicts to keep this PR open.
          close-pr-message: >
            This pull request has been automatically closed due to inactivity.
            Please feel free to reopen it when you're ready to continue.
          
          # Exempt labels
          exempt-issue-labels: 'pinned,security,roadmap,enhancement'
          exempt-pr-labels: 'pinned,security,work-in-progress'
          
          # Operations per run (to avoid rate limiting)
          operations-per-run: 100

